using System.Globalization;
using System.Text;
using AudioTunePro.Core.Models;

namespace AudioTunePro.Core.Services;

/// <summary>
/// Renders an <see cref="EqEngine"/> state into an Equalizer APO configuration
/// snippet. AudioTune Pro never touches the user's main config.txt directly for
/// filter data — it writes this snippet to its own include file and only ever
/// adds a single "Include:" line to config.txt (see EqualizerApoInstallService),
/// so AudioTune Pro can coexist with any other Equalizer APO customization.
/// </summary>
public static class EqualizerApoConfigGenerator
{
    public static string Generate(EqEngine engine)
    {
        var sb = new StringBuilder();
        var culture = CultureInfo.InvariantCulture;

        sb.AppendLine("# Generated by AudioTune Pro — do not edit by hand.");
        sb.AppendLine("# Changes made here will be overwritten the next time AudioTune Pro applies a profile.");
        sb.AppendLine($"# Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        if (!engine.EnableEqualizer)
        {
            sb.AppendLine("# Equalizer disabled — passthrough (unity gain).");
            sb.AppendLine("Preamp: 0.0 dB");
            return sb.ToString();
        }

        double autoTrim = AutoGainLimiter.ComputeTrimDb(engine);
        double totalPreamp = engine.PreampDb + autoTrim;

        if (autoTrim < -0.05)
        {
            sb.AppendLine(FormattableString.Invariant(
                $"# Clipping protection trimmed preamp by {autoTrim:F1} dB to keep peaks under {engine.Limiter.CeilingDb:F1} dBFS."));
        }

        sb.AppendLine(FormattableString.Invariant($"Preamp: {totalPreamp:F2} dB"));
        sb.AppendLine();

        // 10-band graphic EQ as a single interpolated GraphicEQ line — this is the
        // low-CPU path in Equalizer APO (one spline filter instead of N peaking filters).
        var points = engine.Bands
            .Select(b => FormattableString.Invariant($"{b.FrequencyHz:0} {b.GainDb:F1}"))
            .ToArray();
        sb.AppendLine("GraphicEQ: " + string.Join("; ", points));
        sb.AppendLine();

        int filterIndex = 1;
        if (Math.Abs(engine.BassDb) > 0.001)
        {
            sb.AppendLine(FormattableString.Invariant(
                $"Filter {filterIndex++}: ON LSC Fc 150 Hz Gain {engine.BassDb:F1} dB Q 0.9"));
        }
        if (Math.Abs(engine.TrebleDb) > 0.001)
        {
            sb.AppendLine(FormattableString.Invariant(
                $"Filter {filterIndex++}: ON HSC Fc 6500 Hz Gain {engine.TrebleDb:F1} dB Q 0.9"));
        }

        return sb.ToString();
    }
}
